=== JSalmon11/Gesti-nFaltas/1DAM/Lenguaje de marcas/XML/xml+dtd/CV/cv.dtd
<!ELEMENT cv (datospersonales, cursos, conocimientos, experiencia_profesional)>
<!ELEMENT datospersonales
 (apellidos, nombre, nacimiento, direccion?, codigo_postal?, ciudad?, pais?, telefono?, email?)>
<!ELEMENT cursos (curso+)>
<!ELEMENT conocimientos (tecnico*, idioma*)>
<!ELEMENT experiencia_profesional (puesto+)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (fijo | movil) #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT curso EMPTY>
<!ATTLIST curso
   fecha_inicio CDATA #REQUIRED
   fecha_fin CDATA #IMPLIED
   nombre CDATA #REQUIRED
   descripcion CDATA #IMPLIED>
<!ELEMENT tecnico EMPTY>
<!ATTLIST tecnico
   nombre CDATA #REQUIRED
   descripcion CDATA #IMPLIED>
<!ELEMENT idioma EMPTY>
<!ATTLIST idioma
   nombre CDATA #REQUIRED
   nivel (A1|A2|B1|B2|C1|C2) #REQUIRED>
<!ELEMENT puesto (funciones, tecnologias)>
<!ATTLIST experiencia_profesional
   fecha_inicio CDATA #REQUIRED
   fecha_fin CDATA #IMPLIED
   empresa  CDATA #REQUIRED
   cargo CDATA #REQUIRED>
<!ELEMENT funciones (funcion+)>
<!ELEMENT tecnologias (tecnologia+)>
<!ELEMENT funcion (#PCDATA)>
<!ELEMENT tecnologia (#PCDATA)>

=== JSalmon11/Gesti-nFaltas/1DAM/Lenguaje de marcas/XML/xml+dtd/CV/cv.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cv PUBLIC "DTD" "cv.dtd">
<cv>
<datospersonales>
  <apellidos>Ojeda Torres</apellidos>
  <nombre>Sergio</nombre>
  <nacimiento>22/03/2002</nacimiento>
  <direccion>Calle de la Buena Vida, 23</direccion>
  <codigo_postal>20517</codigo_postal>
  <ciudad>Madriz</ciudad>
  <pais>Espania</pais>
  <telefono tipo="movil">123456679</telefono>
  <email>buenavida123@gmail.com</email>
</datospersonales>
<cursos>
  <curso fecha_inicio="Ayer" fecha_fin="Hoy" nombre="Sergio" descripcion="aburrido"/>
</cursos>
<conocimientos>
  <tecnico nombre="Sergio" descripcion="buenisimo"/>
  <idioma nombre="ingles" nivel="B2"/>
</conocimientos>
<experiencia_profesional fecha_inicio="Ayer" fecha_fin="Hoy" empresa="HalaMadrid" cargo="recogepelotas">
  <puesto>
    <funciones>
      <funcion>Trabajar</funcion>
    </funciones>
    <tecnologias>
      <tecnologia>Moderna</tecnologia>
    </tecnologias>
    </puesto>
</experiencia_profesional>
</cv>
